__author__ = 'ryan'


boot = {
  "user": {"num": 1, "children": []},
  "consumer": {"num": 1, "children": []},
  "config": {"num": 5, "children": []},
  "recordv2": {"num": 12, "children": []},
  "reflection": {"num": 1, "children": []},
  "json": {"num": 6, "children": ["recordv2","reflection"]},
  "base2": {"num": 30, "children": ["config","json"]},
  "base-min": {"num": 3, "children": ["base2","config"]},
  "base": {"num": 21, "children": ["base-min","config","consumer","user","json","base2"]},
  "zookeeper": {"num": 5, "children": ["base","base2","config"]},
  "geo-min": {"num": 5, "children": ["base-min"]},
  "geo": {"num": 11, "children": ["base","base2","config","json","geo-min"]},
  "i18n": {"num": 8, "children": ["base2"]},
  "string": {"num": 2, "children": ["i18n"]},
  "lib2": {"num": 1, "children": ["base2"]},
  "net-base": {"num": 7, "children": ["base2"]},
  "client": {"num": 2, "children": ["base2","config","net-base"]},
  "graphite-hadoop": {"num": 3, "children": ["base2"]},
  "graphite": {"num": 2, "children": ["base","config","graphite-hadoop","client"]},
  "temphtml": {"num": 1, "children": []},
  "acl": {"num": 2, "children": []},
  "s3-legacy": {"num": 2, "children": ["base-min","user","config","consumer","acl"]},
  "images": {"num": 6, "children": ["base","base2","config","s3-legacy"]},
  "record": {"num": 36, "children": ["base2","config","string","i18n","recordv2","geo","temphtml","images","base"]},
  "indexes": {"num": 1, "children": ["record"]},
  "concurrent": {"num": 1, "children": []},
  "lib": {"num": 6, "children": ["config","s3-legacy","base2","consumer","user","concurrent"]},
  "weblogger": {"num": 1, "children": ["base-min","lib"]},
  "lift_cookie": {"num": 1, "children": ["weblogger"]},
  "services": {"num": 19, "children": ["lift_cookie","config","user","consumer","geo","base","base2"]},
  "mongo": {"num": 5, "children": ["base","base2","services","record"]},
  "boot": {"num": 8, "children": ["lib2","base2","services","mongo","graphite","zookeeper","indexes","record","base"]},
}


frontend_pages = {
  "webdebug": {"num": 1, "children": []},
  "model": {"num": 27, "children": []},
  "service": {"num": 19, "children": ["model"]},
  "types-gen": {"num": 1, "children": []},
  "types": {"num": 2, "children": ["types-gen"]},
  "base": {"num": 2, "children": ["types-gen"]},
  "math": {"num": 1, "children": ["types-gen"]},
  "category": {"num": 1, "children": []},
  "twofishes": {"num": 1, "children": []},
  "query": {"num": 1, "children": ["types","types-gen","twofishes"]},
  "venue": {"num": 26, "children": ["category","base","query","types-gen","math"]},
  "renderedoutputs": {"num": 6, "children": []},
  "renderedmodels": {"num": 5, "children": ["renderedoutputs","model"]},
  "inputs": {"num": 1, "children": ["renderedoutputs"]},
  "drag": {"num": 77, "children": ["renderedmodels","inputs"]},
  "i18n": {"num": 3, "children": []},
  "uris": {"num": 1, "children": []},
  "api": {"num": 8, "children": ["service"]},
  "notifier": {"num": 1, "children": []},
  "queue2": {"num": 1, "children": []},
  "finagle": {"num": 2, "children": []},
  "features": {"num": 5, "children": []},
  "activities": {"num": 1, "children": []},
  "util": {"num": 4, "children": ["activities","types","venue","queue2"]},
  "server": {"num": 20, "children": ["finagle"]},
  "http": {"num": 6, "children": ["util","api","server"]},
  "dynconfig": {"num": 2, "children": []},
  "logging": {"num": 1, "children": []},
  "request": {"num": 1, "children": ["logging","api","http","renderedmodels"]},
  "clock": {"num": 2, "children": []},
  "soy-util": {"num": 2, "children": ["renderedoutputs"]},
  "resource": {"num": 2, "children": []},
  "resource-less": {"num": 1, "children": ["resource"]},
  "readonly": {"num": 4, "children": []},
  "localization": {"num": 2, "children": ["features"]},
  "throttles": {"num": 2, "children": []},
  "appconfig": {"num": 1, "children": ["throttles"]},
  "chrome": {"num": 2, "children": []},
  "lib-soy": {"num": 13, "children": ["uris"]},
  "base-fileset": {"num": 1, "children": []},
  "soy-resource": {"num": 1, "children": ["base-fileset","resource"]},
  "soy-soy": {"num": 4, "children": ["soy-resource","i18n","lib-soy","soy-util","base-fileset"]},
  "services": {"num": 6, "children": ["renderedmodels","localization","readonly","throttles","soy-soy","clock","resource","dynconfig","http","request"]},
  "layouts": {"num": 1, "children": ["services","drag","inputs","soy-soy","renderedmodels"]},
  "homepage": {"num": 4, "children": ["renderedoutputs","inputs","soy-soy","drag","renderedmodels"]},
  "javascript": {"num": 5, "children": ["resource","soy-soy"]},
  "concrete": {"num": 1, "children": ["resource","resource-less","soy-resource","javascript"]},
  "emails": {"num": 1, "children": []},
  "oauth": {"num": 1, "children": []},
  "webfrontend": {"num": 16, "children": ["services","server","oauth","emails","resource","renderedmodels","notifier","soy-soy","logging","javascript","api","concrete","request","http","webdebug","inputs","drag"]},
  "mobile": {"num": 1, "children": []},
  "path": {"num": 1, "children": []},
  "tracersettings": {"num": 1, "children": ["mobile","util","path"]},
  "frontend-chrome": {"num": 5, "children": ["renderedmodels","server","services","resource","chrome","soy-soy","api","javascript","appconfig","concrete","uris","renderedoutputs","http","webdebug","tracersettings","inputs","webfrontend","drag"]},
  "pages": {"num": 11, "children": ["renderedmodels","server","services","homepage","resource","soy-soy","layouts","api","javascript","webfrontend","concrete","frontend-chrome","renderedoutputs","request","http","webdebug","inputs","drag"]},
}

boot_small = {
  "zookeeper": {"num": 5, "children": []},
  "lib2": {"num": 1, "children": []},
  "base": {"num": 7, "children": []},
  "client": {"num": 2, "children": ["base"]},
  "graphite-hadoop": {"num": 3, "children": []},
  "graphite": {"num": 2, "children": ["graphite-hadoop","client"]},
  "indexes": {"num": 1, "children": []},
  "concurrent": {"num": 1, "children": []},
  "lib": {"num": 6, "children": ["concurrent"]},
  "weblogger": {"num": 1, "children": ["lib"]},
  "lift_cookie": {"num": 1, "children": ["weblogger"]},
  "services": {"num": 19, "children": ["lift_cookie"]},
  "mongo": {"num": 5, "children": ["services"]},
  "boot": {"num": 8, "children": ["services","indexes","lib2","mongo","zookeeper","graphite"]},
}

record = {
  "user": {"num": 1, "children": []},
  "consumer": {"num": 1, "children": []},
  "config": {"num": 5, "children": []},
  "recordv2": {"num": 12, "children": []},
  "reflection": {"num": 1, "children": []},
  "json": {"num": 6, "children": ["recordv2","reflection"]},
  "base2": {"num": 30, "children": ["config","json"]},
  "base-min": {"num": 3, "children": ["base2","config"]},
  "base": {"num": 21, "children": ["consumer","base2","config","base-min","json","user"]},
  "geo-min": {"num": 5, "children": ["base-min"]},
  "geo": {"num": 11, "children": ["base","base2","json","config","geo-min"]},
  "i18n": {"num": 8, "children": ["base2"]},
  "string": {"num": 2, "children": ["i18n"]},
  "temphtml": {"num": 1, "children": []},
  "acl": {"num": 2, "children": []},
  "s3-legacy": {"num": 2, "children": ["base-min","user","config","consumer","acl"]},
  "images": {"num": 6, "children": ["base","base2","config","s3-legacy"]},
  "record": {"num": 36, "children": ["base2","geo","config","string","temphtml","base","images","recordv2","i18n"]},
}

record_small = {
  "geo-min": {"num": 5, "children": []},
  "geo": {"num": 11, "children": ["geo-min"]},
  "i18n": {"num": 8, "children": []},
  "string": {"num": 2, "children": ["i18n"]},
  "temphtml": {"num": 1, "children": []},
  "acl": {"num": 2, "children": []},
  "s3-legacy": {"num": 2, "children": ["acl"]},
  "images": {"num": 6, "children": ["s3-legacy"]},
  "record": {"num": 36, "children": []},
}

base2 = {
  "config": {"num": 5, "children": []},
  "recordv2": {"num": 12, "children": []},
  "reflection": {"num": 1, "children": []},
  "json": {"num": 6, "children": ["recordv2","reflection"]},
  "base2": {"num": 30, "children": ["config","json"]},
}

hairball_raw = {
  "core.src.main.scala.com.foursquare.activities.id": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.config.config": {"num": 5, "children": []},
  "core.src.main.scala.com.foursquare.recordv2.recordv2": {"num": 12, "children": []},
  "web.src.main.resources.soy-webdebug-templates.webdebug.soy_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.resources.soy-emails.soy-emails.soy_codegen": {"num": 25, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.roguev2.roguev2": {"num": 2, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.reflection.reflection": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.json.json": {"num": 6, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.reflection.reflection"]},
  "core.src.main.scala.com.foursquare.base2.base2": {"num": 30, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.json.json"]},
  "core.src.main.scala.com.foursquare.base.base-min": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config"]},
  "core.src.main.thrift.com.foursquare.types.types.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.types.types": {"num": 2, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.venue.category.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.venue.tiny.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.venue.category.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.specials2.specials2.scala_record_codegen": {"num": 4, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.venue.tiny.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.specials2.service.service.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.specials2.specials2.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.specials2.service.service": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.thrift.com.foursquare.specials2.service.service.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.base.base.scala_record_codegen": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.math.math.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.logs.logs.scala_record_codegen": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.tip.tip.scala_record_codegen": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.uva.uva.scala_record_codegen": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.checkin.checkin.scala_record_codegen": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.experiments.experiments.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.user.user.scala_record_codegen": {"num": 9, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.experiments.experiments.scala_record_codegen","core.src.main.thrift.com.foursquare.checkin.checkin.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.ads.metrics.metrics.scala_record_codegen": {"num": 4, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.game.game.scala_record_codegen": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.payments.payments.scala_record_codegen": {"num": 4, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.thrift.com.foursquare.query.query.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen","core.src.main.scala.com.foursquare.types.types","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen": {"num": 26, "children": ["core.src.main.thrift.com.foursquare.base.base.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen","core.src.main.thrift.com.foursquare.query.query.scala_record_codegen","core.src.main.thrift.com.foursquare.venue.category.scala_record_codegen","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.math.math.scala_record_codegen","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen": {"num": 10, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen","core.src.main.thrift.com.foursquare.ads.metrics.metrics.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.ads.service.service.scala_record_codegen": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen","core.src.main.thrift.com.foursquare.types.types.scala_record_codegen","core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.geo.geo-min": {"num": 5, "children": ["core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.external.googledocs.googledocs": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.thrift.com.foursquare.hfileservice.hfileservice-record.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs": {"num": 6, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "web.src.main.scala.com.foursquare.web.inputs.inputs": {"num": 1, "children": ["core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs"]},
  "core.src.main.scala.com.foursquare.lib.i18n.soy": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.uris.utils": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.thrift.com.foursquare.api2.model.model.scala_record_codegen": {"num": 27, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels": {"num": 5, "children": ["core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.api2.model.model.scala_record_codegen"]},
  "web.src.main.resources.soy-web-templates.drag.soy_codegen": {"num": 77, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","web.src.main.scala.com.foursquare.web.inputs.inputs"]},
  "web.src.main.resources.soy-web-templates.specials2.soy_codegen": {"num": 19, "children": ["core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","web.src.main.scala.com.foursquare.web.inputs.inputs"]},
  "core.src.main.thrift.com.foursquare.api2.service.service.scala_record_codegen": {"num": 19, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.thrift.com.foursquare.api2.model.model.scala_record_codegen"]},
  "core.src.main.thrift.com.foursquare.facebook.facebook.scala_record_codegen": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.queue2.queue2": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.api.util.util": {"num": 4, "children": ["core.src.main.scala.com.foursquare.activities.id","core.src.main.scala.com.foursquare.base.base-min","core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen","core.src.main.scala.com.foursquare.queue2.queue2","core.src.main.scala.com.foursquare.types.types"]},
  "core.src.main.scala.com.foursquare.i18n.i18n": {"num": 8, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.string.string": {"num": 2, "children": ["core.src.main.scala.com.foursquare.i18n.i18n"]},
  "core.src.main.scala.com.foursquare.datetime.datetime": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.i18n.i18n"]},
  "core.src.main.scala.com.foursquare.lib2.lib2": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.net.base.base": {"num": 7, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.net.client.client": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.net.base.base"]},
  "core.src.main.scala.com.foursquare.frontend.api.api": {"num": 8, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.net.client.client","core.src.main.thrift.com.foursquare.api2.service.service.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.instrumentation.notifier.notifier": {"num": 1, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.net.client.client"]},
  "core.src.main.scala.com.foursquare.net.graphite.graphite-hadoop": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.features.support": {"num": 5, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.hfileservice.common.hfileservice-common": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.net.finagle.finagle": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.algorithms.neural_net": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.venue.util.home_venue": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.algorithms.neural_net","core.src.main.scala.com.foursquare.string.string"]},
  "core.src.main.scala.com.foursquare.auth.user": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.auth.consumer": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.base.base": {"num": 21, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.json.json","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.geo.geo": {"num": 11, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.json.json","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.geo.geo-min"]},
  "core.src.main.scala.com.foursquare.services.messages.messages": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.geo.geo","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.geocoder.services.services": {"num": 2, "children": ["core.src.main.scala.com.foursquare.net.client.client","core.src.main.scala.com.foursquare.geo.geo","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen","core.src.main.scala.com.foursquare.services.messages.messages"]},
  "core.src.main.scala.com.foursquare.geocoder.concrete.concrete": {"num": 6, "children": ["core.src.main.scala.com.foursquare.geocoder.services.services","core.src.main.scala.com.foursquare.net.client.client","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen","core.src.main.scala.com.foursquare.services.messages.messages","core.src.main.scala.com.foursquare.geo.geo"]},
  "core.src.main.scala.com.foursquare.net.graphite.graphite": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.net.graphite.graphite-hadoop","core.src.main.scala.com.foursquare.net.client.client"]},
  "core.src.main.scala.com.foursquare.zookeeper.zookeeper": {"num": 5, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config"]},
  "core.src.main.scala.com.foursquare.dynconfig.non-hairball": {"num": 2, "children": ["core.src.main.scala.com.foursquare.zookeeper.zookeeper","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.net.graphite.graphite","core.src.main.scala.com.foursquare.lib2.lib2"]},
  "core.src.main.scala.com.foursquare.cache.cache": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.zookeeper.zookeeper"]},
  "core.src.main.scala.com.foursquare.net.server.server": {"num": 20, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.net.base.base","core.src.main.scala.com.foursquare.json.json","core.src.main.scala.com.foursquare.zookeeper.zookeeper","core.src.main.scala.com.foursquare.net.finagle.finagle"]},
  "core.src.main.scala.com.foursquare.frontend.http.http": {"num": 6, "children": ["core.src.main.scala.com.foursquare.api.util.util","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.frontend.api.api","core.src.main.scala.com.foursquare.net.server.server","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.temphtml.temphtml": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.file.acl": {"num": 2, "children": []},
  "core.src.main.scala.com.foursquare.file.s3-legacy": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.file.acl","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.auth.consumer"]},
  "core.src.main.scala.com.foursquare.images.images": {"num": 6, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.file.s3-legacy"]},
  "core.src.main.scala.com.foursquare.record.record": {"num": 36, "children": ["core.src.main.scala.com.foursquare.geo.geo","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.i18n.i18n","core.src.main.scala.com.foursquare.temphtml.temphtml","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.images.images","core.src.main.scala.com.foursquare.string.string","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.indexes.indexes": {"num": 1, "children": ["core.src.main.scala.com.foursquare.record.record"]},
  "core.src.main.scala.com.foursquare.database.database": {"num": 2, "children": ["core.src.main.scala.com.foursquare.record.record","core.src.main.scala.com.foursquare.recordv2.recordv2"]},
  "core.src.main.scala.com.foursquare.future.future": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.record.record"]},
  "core.src.main.scala.com.foursquare.twilio.twilio": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.record.record","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.net.client.client"]},
  "core.src.main.scala.com.foursquare.concurrent.concurrent": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.lib.lib": {"num": 6, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.concurrent.concurrent","core.src.main.scala.com.foursquare.file.s3-legacy"]},
  "core.src.main.scala.com.foursquare.weblogger.weblogger": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.lib.lib"]},
  "core.src.main.scala.com.foursquare.net.cookie.lift_cookie": {"num": 1, "children": ["core.src.main.scala.com.foursquare.weblogger.weblogger"]},
  "core.src.main.scala.com.foursquare.throttles.services.services": {"num": 19, "children": ["core.src.main.scala.com.foursquare.geo.geo","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.net.cookie.lift_cookie","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.eventlogging.eventlogging": {"num": 9, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.thrift.com.foursquare.logs.logs.scala_record_codegen","core.src.main.scala.com.foursquare.types.types"]},
  "core.src.main.scala.com.foursquare.geocoder.concrete.encumbered_geocoders": {"num": 2, "children": ["core.src.main.scala.com.foursquare.geo.geo","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.services.messages.messages","core.src.main.scala.com.foursquare.net.client.client","core.src.main.scala.com.foursquare.geocoder.concrete.concrete","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.mongo.mongo": {"num": 5, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.record.record"]},
  "core.src.main.scala.com.foursquare.boot.boot": {"num": 8, "children": ["core.src.main.scala.com.foursquare.indexes.indexes","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.lib2.lib2","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.net.graphite.graphite","core.src.main.scala.com.foursquare.mongo.mongo","core.src.main.scala.com.foursquare.record.record","core.src.main.scala.com.foursquare.zookeeper.zookeeper"]},
  "core.src.main.scala.com.foursquare.localization.localization": {"num": 2, "children": ["core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.i18n.i18n","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.features.support"]},
  "core.src.main.scala.com.foursquare.localization.lift-localization": {"num": 1, "children": ["core.src.main.scala.com.foursquare.localization.localization"]},
  "core.src.main.scala.com.foursquare.throttles.concrete.readonly": {"num": 4, "children": ["core.src.main.scala.com.foursquare.zookeeper.zookeeper","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.base2.base2"]},
  "core.src.main.scala.com.foursquare.user.facebook.throttles": {"num": 2, "children": ["core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.throttles.services.services"]},
  "core.src.main.scala.com.foursquare.user.facebook.appconfig": {"num": 1, "children": ["core.src.main.scala.com.foursquare.user.facebook.throttles","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.base.base-min"]},
  "web.src.main.scala.com.foursquare.web.chrome.chrome": {"num": 2, "children": ["core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.throttles.services.services"]},
  "core.src.main.scala.com.foursquare.payments.common.common": {"num": 3, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.throttles.services.services"]},
  "core.src.main.scala.com.foursquare.lib.resource.resource": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.lib.lib"]},
  "core.src.main.scala.com.foursquare.lib.resource.less": {"num": 1, "children": ["core.src.main.scala.com.foursquare.lib.resource.resource"]},
  "core.src.main.scala.com.foursquare.soy.util": {"num": 2, "children": ["core.src.main.scala.com.foursquare.lib.lib","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs"]},
  "core.src.main.scala.com.foursquare.lib.soy.soy": {"num": 13, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.lib.lib","core.src.main.scala.com.foursquare.string.string","core.src.main.scala.com.foursquare.uris.utils"]},
  "core.src.main.scala.com.foursquare.clock.clock": {"num": 2, "children": []},
  "core.src.main.scala.com.foursquare.limiter.limiterblockedservice": {"num": 2, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.clock.clock","core.src.main.scala.com.foursquare.zookeeper.zookeeper"]},
  "core.src.main.scala.com.foursquare.limiter.limiter": {"num": 4, "children": ["core.src.main.scala.com.foursquare.limiter.limiterblockedservice"]},
  "core.src.main.scala.com.foursquare.boot.fslog": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.deploy.uploadstaticresources-lib": {"num": 2, "children": ["core.src.main.scala.com.foursquare.boot.fslog","core.src.main.scala.com.foursquare.lib.lib"]},
  "core.src.main.scala.com.foursquare.emails.emails": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.logging.logging": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.frontend.request.request": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.logging.logging","core.src.main.scala.com.foursquare.frontend.api.api","core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels"]},
  "core.src.main.scala.com.foursquare.file2.file2": {"num": 7, "children": ["core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.logging.logging","core.src.main.scala.com.foursquare.file.acl"]},
  "core.src.main.scala.com.foursquare.hfileservice.client.hfileservice-client": {"num": 2, "children": ["core.src.main.thrift.com.foursquare.hfileservice.hfileservice-record.scala_record_codegen","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.lib2.lib2","core.src.main.thrift.com.foursquare.base.base.scala_record_codegen","core.src.main.scala.com.foursquare.hfileservice.common.hfileservice-common","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.file2.file2","core.src.main.scala.com.foursquare.net.client.client"]},
  "core.src.main.scala.com.foursquare.venue.hfileservice.client.venue-client-lib": {"num": 1, "children": ["core.src.main.thrift.com.foursquare.hfileservice.hfileservice-record.scala_record_codegen","core.src.main.scala.com.foursquare.hfileservice.common.hfileservice-common","core.src.main.thrift.com.foursquare.tip.tip.scala_record_codegen","core.src.main.scala.com.foursquare.lib2.lib2","core.src.main.scala.com.foursquare.hfileservice.client.hfileservice-client","core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen","core.src.main.scala.com.foursquare.types.types"]},
  "core.src.main.scala.com.foursquare.mobile.mobile": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.path.path": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.instrumentation.tracersettings.tracersettings": {"num": 1, "children": ["core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.api.util.util","core.src.main.scala.com.foursquare.path.path","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.mobile.mobile"]},
  "core.src.main.scala.com.foursquare.frontend.filters.filters": {"num": 3, "children": ["core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.path.path"]},
  "core.src.main.scala.com.foursquare.soy.base-fileset": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.soy.resource": {"num": 1, "children": ["core.src.main.scala.com.foursquare.soy.base-fileset","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.lib.resource.resource"]},
  "core.src.main.scala.com.foursquare.soy.soy": {"num": 4, "children": ["core.src.main.scala.com.foursquare.lib.soy.soy","core.src.main.scala.com.foursquare.lib.lib","core.src.main.scala.com.foursquare.soy.resource","core.src.main.scala.com.foursquare.soy.util","core.src.main.scala.com.foursquare.base.base-min","core.src.main.scala.com.foursquare.lib.i18n.soy","core.src.main.scala.com.foursquare.soy.base-fileset"]},
  "core.src.main.scala.com.foursquare.frontend.services.services": {"num": 6, "children": ["core.src.main.scala.com.foursquare.clock.clock","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.i18n.i18n","core.src.main.scala.com.foursquare.throttles.concrete.readonly","core.src.main.scala.com.foursquare.localization.localization","core.src.main.scala.com.foursquare.net.graphite.graphite","core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.frontend.request.request","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.dynconfig.non-hairball","core.src.main.scala.com.foursquare.soy.soy","core.src.main.scala.com.foursquare.user.facebook.throttles","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.frontend.layouts.layouts": {"num": 1, "children": ["web.src.main.scala.com.foursquare.web.inputs.inputs","web.src.main.resources.soy-web-templates.drag.soy_codegen","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.frontend.services.services","core.src.main.scala.com.foursquare.soy.soy","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.soy.lift-soy": {"num": 4, "children": ["core.src.main.scala.com.foursquare.soy.soy","core.src.main.scala.com.foursquare.soy.util","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.localization.lift-localization"]},
  "core.src.main.scala.com.foursquare.lib.i18n.extract-soy-messages": {"num": 1, "children": ["core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.soy.lift-soy","core.src.main.scala.com.foursquare.soy.soy"]},
  "web.src.main.scala.com.foursquare.web.homepage.homepage": {"num": 4, "children": ["core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","web.src.main.scala.com.foursquare.web.inputs.inputs","web.src.main.resources.soy-web-templates.drag.soy_codegen","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.soy.soy"]},
  "core.src.main.scala.com.foursquare.lib.resource.javascript": {"num": 5, "children": ["core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.soy.soy"]},
  "core.src.main.scala.com.foursquare.lib.resource.concrete": {"num": 1, "children": ["core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.lib.resource.less","core.src.main.scala.com.foursquare.lib.resource.javascript","core.src.main.scala.com.foursquare.soy.resource"]},
  "core.src.main.scala.com.foursquare.lib.resource.resource-service": {"num": 2, "children": ["core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.soy.lift-soy"]},
  "core.src.main.scala.com.foursquare.oauth.webtoken": {"num": 1, "children": []},
  "core.src.main.scala.com.foursquare.frontend.web.webfrontend": {"num": 16, "children": ["core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.emails.emails","core.src.main.scala.com.foursquare.lib.resource.javascript","core.src.main.scala.com.foursquare.instrumentation.notifier.notifier","web.src.main.resources.soy-webdebug-templates.webdebug.soy_codegen","web.src.main.scala.com.foursquare.web.inputs.inputs","core.src.main.scala.com.foursquare.frontend.api.api","web.src.main.resources.soy-web-templates.drag.soy_codegen","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.logging.logging","core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.frontend.request.request","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.net.server.server","core.src.main.scala.com.foursquare.soy.soy","core.src.main.scala.com.foursquare.oauth.webtoken","core.src.main.scala.com.foursquare.frontend.services.services","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.frontend.chrome.chrome": {"num": 5, "children": ["core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.frontend.api.api","core.src.main.scala.com.foursquare.lib.resource.javascript","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.net.server.server","web.src.main.scala.com.foursquare.web.inputs.inputs","web.src.main.scala.com.foursquare.web.chrome.chrome","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.instrumentation.tracersettings.tracersettings","core.src.main.scala.com.foursquare.user.facebook.appconfig","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.uris.utils","core.src.main.scala.com.foursquare.soy.soy","web.src.main.resources.soy-webdebug-templates.webdebug.soy_codegen","web.src.main.resources.soy-web-templates.drag.soy_codegen","core.src.main.scala.com.foursquare.frontend.web.webfrontend","core.src.main.scala.com.foursquare.frontend.services.services","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.frontend.pages.pages": {"num": 11, "children": ["core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.frontend.api.api","core.src.main.scala.com.foursquare.lib.resource.javascript","web.src.main.scala.com.foursquare.web.homepage.homepage","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.frontend.services.services","web.src.main.scala.com.foursquare.web.inputs.inputs","core.src.main.scala.com.foursquare.json.json","web.src.main.resources.soy-web-templates.drag.soy_codegen","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.frontend.layouts.layouts","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.frontend.http.http","core.src.main.scala.com.foursquare.frontend.request.request","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.net.server.server","core.src.main.scala.com.foursquare.soy.soy","web.src.main.resources.soy-webdebug-templates.webdebug.soy_codegen","core.src.main.scala.com.foursquare.frontend.web.webfrontend","core.src.main.scala.com.foursquare.frontend.chrome.chrome","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.specials2.pages.pages": {"num": 2, "children": ["core.src.main.thrift.com.foursquare.specials2.service.service.scala_record_codegen","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","web.src.main.scala.com.foursquare.web.inputs.inputs","core.src.main.scala.com.foursquare.frontend.pages.pages","core.src.main.scala.com.foursquare.specials2.service.service","web.src.main.resources.soy-web-templates.specials2.soy_codegen"]},
  "core.src.main.scala.com.foursquare.frontend.server.frontendserver": {"num": 4, "children": ["core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.eventlogging.eventlogging","core.src.main.scala.com.foursquare.instrumentation.notifier.notifier","core.src.main.scala.com.foursquare.frontend.pages.pages","core.src.main.scala.com.foursquare.net.graphite.graphite","core.src.main.scala.com.foursquare.frontend.filters.filters","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.frontend.renderedmodels.renderedmodels","core.src.main.scala.com.foursquare.specials2.pages.pages"]},
  "core.src.main.scala.com.foursquare.lib.resource.compile-prod-javascript-lib": {"num": 1, "children": ["core.src.main.scala.com.foursquare.lib.resource.concrete","core.src.main.scala.com.foursquare.lib.resource.resource-service","core.src.main.scala.com.foursquare.localization.lift-localization","core.src.main.scala.com.foursquare.frontend.server.frontendserver","core.src.main.scala.com.foursquare.lib.lib","core.src.main.scala.com.foursquare.soy.lift-soy","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.lib.resource.resource","core.src.main.scala.com.foursquare.soy.soy","core.src.main.scala.com.foursquare.frontend.services.services"]},
  "core.src.main.scala.com.foursquare.hairball": {"num": 842, "children": ["core.src.main.scala.com.foursquare.lib.soy.soy","core.src.main.scala.com.foursquare.mobile.mobile","core.src.main.thrift.com.foursquare.user.user.scala_record_codegen","core.src.main.thrift.com.foursquare.ads.metrics.metrics.scala_record_codegen","core.src.main.scala.com.foursquare.json.json","core.src.main.scala.com.foursquare.localization.localization","core.src.main.scala.com.foursquare.file2.file2","core.src.main.scala.com.foursquare.limiter.limiter","core.src.main.scala.com.foursquare.localization.lift-localization","core.src.main.scala.com.foursquare.lib.i18n.soy","core.src.main.scala.com.foursquare.twilio.twilio","core.src.main.scala.com.foursquare.external.googledocs.googledocs","core.src.main.scala.com.foursquare.weblogger.weblogger","core.src.main.scala.com.foursquare.emails.emails","core.src.main.thrift.com.foursquare.game.game.scala_record_codegen","core.src.main.scala.com.foursquare.database.database","core.src.main.scala.com.foursquare.future.future","core.src.main.scala.com.foursquare.record.record","core.src.main.scala.com.foursquare.lib.resource.compile-prod-javascript-lib","core.src.main.scala.com.foursquare.soy.lift-soy","core.src.main.scala.com.foursquare.geocoder.concrete.encumbered_geocoders","core.src.main.scala.com.foursquare.mongo.mongo","core.src.main.thrift.com.foursquare.ads.service.service.scala_record_codegen","core.src.main.scala.com.foursquare.i18n.i18n","core.src.main.scala.com.foursquare.config.config","core.src.main.scala.com.foursquare.path.path","core.src.main.scala.com.foursquare.net.server.server","core.src.main.scala.com.foursquare.temphtml.temphtml","core.src.main.thrift.com.foursquare.base.base.scala_record_codegen","core.src.main.scala.com.foursquare.deploy.uploadstaticresources-lib","core.src.main.scala.com.foursquare.payments.common.common","core.src.main.scala.com.foursquare.user.facebook.appconfig","core.src.main.scala.com.foursquare.geocoder.services.services","core.src.main.scala.com.foursquare.roguev2.roguev2","core.src.main.thrift.com.foursquare.payments.payments.scala_record_codegen","core.src.main.thrift.com.foursquare.checkin.checkin.scala_record_codegen","core.src.main.scala.com.foursquare.venue.util.home_venue","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.thrift.com.foursquare.twofishes.twofishes.scala_record_codegen","core.src.main.scala.com.foursquare.instrumentation.tracersettings.tracersettings","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.types.types","core.src.main.scala.com.foursquare.clock.clock","core.src.main.thrift.com.foursquare.venue.venue.scala_record_codegen","core.src.main.scala.com.foursquare.geo.geo","core.src.main.scala.com.foursquare.net.graphite.graphite","core.src.main.scala.com.foursquare.hfileservice.client.hfileservice-client","core.src.main.scala.com.foursquare.auth.consumer","core.src.main.scala.com.foursquare.auth.user","core.src.main.scala.com.foursquare.eventlogging.eventlogging","core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen","core.src.main.thrift.com.foursquare.facebook.facebook.scala_record_codegen","core.src.main.scala.com.foursquare.zookeeper.zookeeper","core.src.main.scala.com.foursquare.services.messages.messages","core.src.main.resources.soy-emails.soy-emails.soy_codegen","core.src.main.scala.com.foursquare.hfileservice.common.hfileservice-common","core.src.main.scala.com.foursquare.concurrent.concurrent","core.src.main.thrift.com.foursquare.hfileservice.hfileservice-record.scala_record_codegen","core.src.main.scala.com.foursquare.string.string","core.src.main.scala.com.foursquare.cache.cache","core.src.main.scala.com.foursquare.dynconfig.non-hairball","core.src.main.scala.com.foursquare.geocoder.concrete.concrete","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.features.support","core.src.main.scala.com.foursquare.instrumentation.notifier.notifier","core.src.main.thrift.com.foursquare.tip.tip.scala_record_codegen","core.src.main.scala.com.foursquare.lib.i18n.extract-soy-messages","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.lib2.lib2","core.src.main.thrift.com.foursquare.query.query.scala_record_codegen","core.src.main.scala.com.foursquare.datetime.datetime","core.src.main.scala.com.foursquare.lib.lib","core.src.main.scala.com.foursquare.activities.id","core.src.main.scala.com.foursquare.boot.boot","core.src.main.scala.com.foursquare.queue2.queue2","core.src.main.scala.com.foursquare.file.s3-legacy","core.src.main.thrift.com.foursquare.uva.uva.scala_record_codegen","core.src.main.scala.com.foursquare.api.util.util","core.src.main.scala.com.foursquare.images.images","core.src.main.scala.com.foursquare.uris.utils","core.src.main.scala.com.foursquare.oauth.webtoken","core.src.main.scala.com.foursquare.venue.hfileservice.client.venue-client-lib","core.src.main.scala.com.foursquare.user.facebook.throttles","core.src.main.scala.com.foursquare.logging.logging"]},
  "core.src.main.scala.com.foursquare.ads.model.model": {"num": 0, "children": ["core.src.main.scala.com.foursquare.hairball"]},
  "core.src.main.scala.com.foursquare.ads.public.public": {"num": 0, "children": ["core.src.main.scala.com.foursquare.features.support","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.model.model"]},
  "core.src.main.scala.com.foursquare.ads.finders.public.public": {"num": 0, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.model.model"]},
  "core.src.main.scala.com.foursquare.ads.metrics.metrics": {"num": 4, "children": ["core.src.main.scala.com.foursquare.hairball"]},
  "core.src.main.scala.com.foursquare.ads.actions.public.public": {"num": 0, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.features.support","core.src.main.scala.com.foursquare.ads.model.model","core.src.main.scala.com.foursquare.ads.metrics.metrics","core.src.main.scala.com.foursquare.ads.public.public"]},
  "core.src.main.scala.com.foursquare.ads.actions.internal.internal": {"num": 3, "children": ["core.src.main.scala.com.foursquare.ads.metrics.metrics","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.model.model","core.src.main.scala.com.foursquare.ads.public.public","core.src.main.scala.com.foursquare.ads.actions.public.public","core.src.main.scala.com.foursquare.ads.finders.public.public"]},
  "core.src.main.scala.com.foursquare.ads.util.util": {"num": 9, "children": ["core.src.main.scala.com.foursquare.ads.public.public","core.src.main.scala.com.foursquare.ads.actions.internal.internal","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.metrics.metrics","core.src.main.scala.com.foursquare.ads.model.model","core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen","core.src.main.scala.com.foursquare.ads.actions.public.public","core.src.main.scala.com.foursquare.ads.finders.public.public","core.src.main.scala.com.foursquare.types.types"]},
  "core.src.main.scala.com.foursquare.ads.queue.queue": {"num": 1, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.util.util","core.src.main.scala.com.foursquare.types.types","core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen"]},
  "core.src.main.scala.com.foursquare.ads.model2.model2": {"num": 1, "children": ["core.src.main.scala.com.foursquare.hairball"]},
  "core.src.main.scala.com.foursquare.ads.frontend.frontend": {"num": 2, "children": ["core.src.main.scala.com.foursquare.ads.util.util","core.src.main.scala.com.foursquare.recordv2.recordv2","core.src.main.scala.com.foursquare.hairball","core.src.main.thrift.com.foursquare.ads.model.model.scala_record_codegen","core.src.main.scala.com.foursquare.ads.model2.model2","core.src.main.scala.com.foursquare.string.string","core.src.main.scala.com.foursquare.clock.clock","core.src.main.scala.com.foursquare.renderedoutputs.renderedoutputs","core.src.main.scala.com.foursquare.types.types","core.src.main.scala.com.foursquare.base.base-min"]},
  "core.src.main.scala.com.foursquare.ads.actions.concrete.concrete": {"num": 9, "children": ["core.src.main.scala.com.foursquare.ads.util.util","core.src.main.scala.com.foursquare.features.support","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.metrics.metrics","core.src.main.scala.com.foursquare.ads.model.model","core.src.main.scala.com.foursquare.ads.model2.model2","core.src.main.scala.com.foursquare.ads.public.public","core.src.main.scala.com.foursquare.queue2.queue2","core.src.main.scala.com.foursquare.ads.actions.public.public","core.src.main.scala.com.foursquare.ads.finders.public.public"]},
  "core.src.main.scala.com.foursquare.ads.task.task": {"num": 7, "children": ["core.src.main.scala.com.foursquare.ads.actions.concrete.concrete","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.ads.model.model","core.src.main.scala.com.foursquare.ads.public.public","core.src.main.scala.com.foursquare.ads.actions.public.public","core.src.main.scala.com.foursquare.ads.actions.internal.internal"]},
  "core.src.main.scala.com.foursquare.ads.json.json": {"num": 1, "children": ["core.src.main.scala.com.foursquare.hairball"]},
  "core.src.main.scala.com.foursquare.displaymodels.factories.activities.activities": {"num": 10, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.localization.localization","core.src.main.scala.com.foursquare.features.support"]},
  "core.src.main.scala.com.foursquare.displaymodels.factories.notifications.emails.emails": {"num": 17, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.clock.clock","core.src.main.scala.com.foursquare.localization.localization"]},
  "core.src.main.scala.com.foursquare.displaymodels.factories.notifications.notifications": {"num": 14, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.displaymodels.factories.notifications.emails.emails","core.src.main.scala.com.foursquare.clock.clock","core.src.main.scala.com.foursquare.localization.localization"]},
  "core.src.main.scala.com.foursquare.displaymodels.factories.factories": {"num": 3, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.displaymodels.factories.notifications.emails.emails","core.src.main.scala.com.foursquare.base2.base2","core.src.main.scala.com.foursquare.displaymodels.factories.activities.activities","core.src.main.scala.com.foursquare.displaymodels.factories.notifications.notifications","core.src.main.scala.com.foursquare.features.support"]},
  "core.src.main.scala.com.foursquare.payments.models.models": {"num": 6, "children": ["core.src.main.scala.com.foursquare.hairball"]},
  "core.src.main.scala.com.foursquare.indexes.concrete": {"num": 2, "children": ["core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.payments.models.models","core.src.main.scala.com.foursquare.record.record"]},
  "core.src.main.scala.com.foursquare.tracking.tracking": {"num": 9, "children": ["core.src.main.scala.com.foursquare.logging.logging","core.src.main.scala.com.foursquare.throttles.services.services","core.src.main.scala.com.foursquare.hairball","core.src.main.scala.com.foursquare.base.base","core.src.main.scala.com.foursquare.api.util.util","core.src.main.scala.com.foursquare.base2.base2"]},
}

hairball = {
  'soy.resource': {'num': 1, 'children': ['base-fileset', 'base2', 'resource.resource']},
  'features': {'num': 5, 'children': ['base2']},
  'uva': {'num': 2, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'fslog': {'num': 1, 'children': []},
  'tracersettings': {'num': 1, 'children': ['config', 'throttles.services', 'api.util', 'path', 'auth.user', 'base2', 'mobile']},
  'actions.public': {'num': 0, 'children': ['hairball', 'features', 'scala.model', 'scala.metrics', 'public']},
  'path': {'num': 1, 'children': []},
  'thrift.facebook': {'num': 1, 'children': ['base-min', 'recordv2']},
  'notifier': {'num': 1, 'children': ['config', 'base2', 'net.client']},
  'task': {'num': 7, 'children': ['ads.concrete', 'hairball', 'scala.model', 'public', 'actions.public', 'internal']},
  'json': {'num': 6, 'children': ['recordv2', 'reflection']},
  'tracking': {'num': 9, 'children': ['logging', 'throttles.services', 'hairball', 'scala.base.base', 'api.util', 'base2']},
  'consumer': {'num': 1, 'children': []},
  'ads.util': {'num': 9, 'children': ['public', 'internal', 'hairball', 'scala.metrics', 'scala.model', 'thrift.ads.model', 'actions.public', 'finders', 'scala.types']},
  'homepage': {'num': 4, 'children': ['renderedoutputs', 'throttles.services', 'renderedmodels', 'inputs', 'drag', 'auth.user', 'soy.soy']},
  'thrift.user': {'num': 9, 'children': ['base-min', 'recordv2', 'experiments', 'checkin', 'thrift.types']},
  'cache': {'num': 3, 'children': ['base2', 'config', 'zookeeper']},
  'encumbered_geocoders': {'num': 2, 'children': ['geo.geo', 'throttles.services', 'messages', 'net.client', 'geocoder.concrete.concrete', 'twofishes']},
  'limiterblockedservice': {'num': 2, 'children': ['base2', 'clock', 'zookeeper']},
  'home_venue': {'num': 1, 'children': ['base2', 'algorithms', 'string']},
  'game': {'num': 3, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'net.base': {'num': 7, 'children': ['base2']},
  'hfileservice-record': {'num': 1, 'children': ['base-min', 'recordv2']},
  'base-fileset': {'num': 1, 'children': []},
  'category': {'num': 1, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'zookeeper': {'num': 5, 'children': ['scala.base.base', 'base2', 'config']},
  'ads.frontend': {'num': 2, 'children': ['ads.util', 'recordv2', 'hairball', 'thrift.ads.model', 'model2', 'string', 'clock', 'renderedoutputs', 'scala.types', 'base-min']},
  'base2': {'num': 30, 'children': ['config', 'json']},
  'graphite.graphite': {'num': 2, 'children': ['scala.base.base', 'config', 'graphite-hadoop', 'net.client']},
  'api2.model': {'num': 27, 'children': ['base-min', 'recordv2']},
  'uris': {'num': 1, 'children': ['base-min']},
  'soy-emails': {'num': 25, 'children': ['recordv2']},
  'limiter.limiter': {'num': 4, 'children': ['limiterblockedservice']},
  'displaymodels.emails': {'num': 17, 'children': ['hairball', 'base2', 'clock', 'localization.localization']},
  'geocoder.services': {'num': 2, 'children': ['net.client', 'geo.geo', 'twofishes', 'messages']},
  'lib2': {'num': 1, 'children': ['base2']},
  'images': {'num': 6, 'children': ['scala.base.base', 'base2', 'config', 's3-legacy']},
  'boot.boot': {'num': 8, 'children': ['indexes.indexes', 'base2', 'throttles.services', 'lib2', 'scala.base.base', 'graphite.graphite', 'mongo', 'record', 'zookeeper']},
  'i18n.soy': {'num': 3, 'children': ['base-min']},
  'external': {'num': 2, 'children': ['base-min', 'base2']},
  'lib.soy.soy': {'num': 13, 'children': ['base-min', 'lib.lib', 'string', 'uris']},
  'scala.types': {'num': 2, 'children': ['recordv2', 'thrift.types']},
  'experiments': {'num': 1, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'frontend.services': {'num': 6, 'children': ['clock', 'throttles.services', 'renderedmodels', 'i18n.i18n', 'readonly', 'localization.localization', 'graphite.graphite', 'http', 'request', 'resource.resource', 'dynconfig', 'soy.soy', 'user.throttles', 'base-min']},
  'ads.json': {'num': 1, 'children': ['hairball']},
  'messages': {'num': 1, 'children': ['scala.base.base', 'geo.geo', 'twofishes']},
  'scala.service': {'num': 2, 'children': ['base2', 'thrift.specials2.service']},
  'eventlogging': {'num': 9, 'children': ['config', 'throttles.services', 'scala.base.base', 'base2', 'logs', 'scala.types']},
  'javascript': {'num': 5, 'children': ['resource.resource', 'soy.soy']},
  'webfrontend': {'num': 16, 'children': ['lib.concrete', 'emails', 'javascript', 'notifier', 'soy-webdebug-templates', 'inputs', 'frontend.api', 'drag', 'recordv2', 'logging', 'http', 'request', 'resource.resource', 'renderedmodels', 'net.server', 'soy.soy', 'oauth', 'frontend.services', 'base-min']},
  'base-min': {'num': 3, 'children': ['base2', 'config']},
  'clock': {'num': 2, 'children': []},
  'notifications.notifications': {'num': 14, 'children': ['hairball', 'base2', 'displaymodels.emails', 'clock', 'localization.localization']},
  'logs': {'num': 2, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'file2': {'num': 7, 'children': ['base2', 'logging', 'acl']},
  'resource-service': {'num': 2, 'children': ['resource.resource', 'lib.concrete', 'lift-soy']},
  'i18n.i18n': {'num': 8, 'children': ['base2']},
  'internal': {'num': 3, 'children': ['scala.metrics', 'hairball', 'scala.model', 'public', 'actions.public', 'finders']},
  'tiny': {'num': 1, 'children': ['base-min', 'recordv2', 'category', 'thrift.types']},
  'hfileservice-client': {'num': 2, 'children': ['hfileservice-record', 'base2', 'lib2', 'thrift.base', 'hfileservice-common', 'scala.base.base', 'file2', 'net.client']},
  'lib.concrete': {'num': 1, 'children': ['resource.resource', 'less', 'javascript', 'soy.resource']},
  'layouts': {'num': 1, 'children': ['inputs', 'drag', 'renderedmodels', 'frontend.services', 'soy.soy', 'base-min']},
  's3-legacy': {'num': 2, 'children': ['base-min', 'auth.user', 'acl', 'config', 'consumer']},
  'indexes.concrete': {'num': 2, 'children': ['hairball', 'models', 'record']},
  'factories.factories': {'num': 3, 'children': ['hairball', 'displaymodels.emails', 'base2', 'displaymodels.activities', 'notifications.notifications', 'features']},
  'lift-soy': {'num': 4, 'children': ['soy.soy', 'soy.util', 'renderedoutputs', 'lift-localization']},
  'renderedmodels': {'num': 5, 'children': ['renderedoutputs', 'recordv2', 'api2.model']},
  'recordv2': {'num': 12, 'children': []},
  'cookie': {'num': 1, 'children': ['weblogger']},
  'thrift.metrics': {'num': 4, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'ads.service': {'num': 2, 'children': ['base-min', 'recordv2', 'venue.venue', 'thrift.types', 'thrift.ads.model']},
  'scala.model': {'num': 0, 'children': ['hairball']},
  'filters': {'num': 3, 'children': ['http', 'base-min', 'path']},
  'id': {'num': 1, 'children': []},
  'venue-client-lib': {'num': 1, 'children': ['hfileservice-record', 'hfileservice-common', 'tip', 'lib2', 'hfileservice-client', 'venue.venue', 'scala.types']},
  'request': {'num': 1, 'children': ['base-min', 'logging', 'frontend.api', 'http', 'renderedmodels']},
  'dynconfig': {'num': 2, 'children': ['zookeeper', 'config', 'graphite.graphite', 'lib2']},
  'soy.soy': {'num': 4, 'children': ['lib.soy.soy', 'lib.lib', 'soy.resource', 'soy.util', 'base-min', 'i18n.soy', 'base-fileset']},
  'thrift.specials2.service': {'num': 1, 'children': ['base-min', 'recordv2', 'specials2.specials2', 'thrift.types']},
  'roguev2': {'num': 2, 'children': ['recordv2']},
  'finders': {'num': 0, 'children': ['hairball', 'scala.model']},
  'mobile': {'num': 1, 'children': []},
  'query': {'num': 1, 'children': ['base-min', 'recordv2', 'twofishes', 'scala.types', 'thrift.types']},
  'graphite-hadoop': {'num': 3, 'children': ['base2']},
  'logging': {'num': 1, 'children': []},
  'model2': {'num': 1, 'children': ['hairball']},
  'geocoder.concrete.concrete': {'num': 6, 'children': ['geocoder.services', 'net.client', 'twofishes', 'messages', 'geo.geo']},
  'frontend.pages': {'num': 11, 'children': ['lib.concrete', 'frontend.api', 'javascript', 'homepage', 'renderedmodels', 'frontend.services', 'inputs', 'json', 'drag', 'recordv2', 'layouts', 'renderedoutputs', 'http', 'request', 'resource.resource', 'net.server', 'soy.soy', 'soy-webdebug-templates', 'webfrontend', 'core.chrome', 'base-min']},
  'readonly': {'num': 4, 'children': ['zookeeper', 'config', 'throttles.services', 'scala.base.base', 'base-min', 'base2']},
  'algorithms': {'num': 1, 'children': ['base2']},
  'hfileservice-common': {'num': 3, 'children': ['base2']},
  'weblogger': {'num': 1, 'children': ['base-min', 'lib.lib']},
  'deploy': {'num': 2, 'children': ['fslog', 'lib.lib']},
  'geo-min': {'num': 5, 'children': ['base-min']},
  'database': {'num': 2, 'children': ['record', 'recordv2']},
  'lib.lib': {'num': 6, 'children': ['config', 'auth.user', 'consumer', 'base2', 'concurrent', 's3-legacy']},
  'compile-prod-javascript-lib': {'num': 1, 'children': ['lib.concrete', 'resource-service', 'lift-localization', 'frontendserver', 'lib.lib', 'lift-soy', 'base2', 'resource.resource', 'soy.soy', 'frontend.services']},
  'web.specials2': {'num': 19, 'children': ['recordv2', 'renderedmodels', 'inputs']},
  'twilio': {'num': 3, 'children': ['scala.base.base', 'base2', 'record', 'config', 'net.client']},
  'scala.metrics': {'num': 4, 'children': ['hairball']},
  'soy.util': {'num': 2, 'children': ['lib.lib', 'renderedoutputs']},
  'renderedoutputs': {'num': 6, 'children': ['base-min', 'recordv2']},
  'twofishes': {'num': 1, 'children': ['base-min', 'recordv2']},
  'api2.service': {'num': 19, 'children': ['base-min', 'recordv2', 'api2.model']},
  'user.throttles': {'num': 2, 'children': ['auth.user', 'consumer', 'throttles.services']},
  'finagle': {'num': 2, 'children': ['base2']},
  'queue2': {'num': 1, 'children': ['base2']},
  'config': {'num': 5, 'children': []},
  'oauth': {'num': 1, 'children': []},
  'specials2.specials2': {'num': 4, 'children': ['base-min', 'recordv2', 'tiny', 'thrift.types']},
  'temphtml': {'num': 1, 'children': []},
  'string': {'num': 2, 'children': ['i18n.i18n']},
  'tip': {'num': 3, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'mongo': {'num': 5, 'children': ['scala.base.base', 'base2', 'throttles.services', 'record']},
  'web.chrome': {'num': 2, 'children': ['auth.user', 'throttles.services']},
  'resource.resource': {'num': 2, 'children': ['base-min', 'lib.lib']},
  'localization.localization': {'num': 2, 'children': ['throttles.services', 'auth.user', 'i18n.i18n', 'consumer', 'base2', 'config', 'features']},
  'soy-webdebug-templates': {'num': 1, 'children': ['recordv2']},
  'displaymodels.activities': {'num': 10, 'children': ['hairball', 'base2', 'localization.localization', 'features']},
  'extract-soy-messages': {'num': 1, 'children': ['scala.base.base', 'lift-soy', 'soy.soy']},
  'thrift.types': {'num': 1, 'children': ['base-min', 'recordv2']},
  'hairball': {'num': 842, 'children': ['lib.soy.soy', 'mobile', 'thrift.user', 'thrift.metrics', 'json', 'localization.localization', 'file2', 'limiter.limiter', 'lift-localization', 'i18n.soy', 'twilio', 'external', 'weblogger', 'emails', 'game', 'database', 'future', 'record', 'compile-prod-javascript-lib', 'lift-soy', 'encumbered_geocoders', 'mongo', 'ads.service', 'i18n.i18n', 'config', 'path', 'net.server', 'temphtml', 'thrift.base', 'deploy', 'payments.common', 'appconfig', 'geocoder.services', 'roguev2', 'thrift.payments', 'checkin', 'home_venue', 'renderedoutputs', 'twofishes', 'tracersettings', 'scala.base.base', 'scala.types', 'clock', 'venue.venue', 'geo.geo', 'graphite.graphite', 'hfileservice-client', 'consumer', 'auth.user', 'eventlogging', 'thrift.ads.model', 'thrift.facebook', 'zookeeper', 'messages', 'soy-emails', 'hfileservice-common', 'concurrent', 'hfileservice-record', 'string', 'cache', 'dynconfig', 'geocoder.concrete.concrete', 'recordv2', 'base2', 'features', 'notifier', 'tip', 'extract-soy-messages', 'throttles.services', 'lib2', 'query', 'datetime', 'lib.lib', 'id', 'boot.boot', 'queue2', 's3-legacy', 'uva', 'api.util', 'images', 'uris', 'oauth', 'venue-client-lib', 'user.throttles', 'logging']},
  'thrift.base': {'num': 2, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'reflection': {'num': 1, 'children': []},
  'lift-localization': {'num': 1, 'children': ['localization.localization']},
  'emails': {'num': 1, 'children': []},
  'specials2.pages': {'num': 2, 'children': ['thrift.specials2.service', 'renderedmodels', 'inputs', 'frontend.pages', 'scala.service', 'web.specials2']},
  'queue': {'num': 1, 'children': ['hairball', 'ads.util', 'scala.types', 'thrift.ads.model']},
  'public': {'num': 0, 'children': ['features', 'hairball', 'scala.model']},
  'frontendserver': {'num': 4, 'children': ['lib.concrete', 'eventlogging', 'notifier', 'frontend.pages', 'graphite.graphite', 'filters', 'resource.resource', 'renderedmodels', 'specials2.pages']},
  'drag': {'num': 77, 'children': ['recordv2', 'renderedmodels', 'inputs']},
  'venue.venue': {'num': 26, 'children': ['thrift.base', 'thrift.types', 'query', 'category', 'recordv2', 'math', 'base-min']},
  'inputs': {'num': 1, 'children': ['renderedoutputs']},
  'net.client': {'num': 2, 'children': ['base2', 'config', 'net.base']},
  'models': {'num': 6, 'children': ['hairball']},
  'throttles.services': {'num': 19, 'children': ['geo.geo', 'config', 'auth.user', 'cookie', 'scala.base.base', 'consumer', 'base2']},
  'core.chrome': {'num': 5, 'children': ['lib.concrete', 'frontend.api', 'javascript', 'renderedmodels', 'net.server', 'inputs', 'web.chrome', 'recordv2', 'tracersettings', 'appconfig', 'renderedoutputs', 'http', 'resource.resource', 'uris', 'soy.soy', 'soy-webdebug-templates', 'drag', 'webfrontend', 'frontend.services', 'base-min']},
  'appconfig': {'num': 1, 'children': ['user.throttles', 'auth.user', 'throttles.services', 'consumer', 'base-min']},
  'frontend.api': {'num': 8, 'children': ['base-min', 'net.client', 'api2.service']},
  'thrift.ads.model': {'num': 10, 'children': ['base-min', 'recordv2', 'venue.venue', 'thrift.metrics', 'thrift.types']},
  'math': {'num': 1, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'payments.common': {'num': 3, 'children': ['base2', 'throttles.services']},
  'net.server': {'num': 20, 'children': ['base2', 'net.base', 'json', 'zookeeper', 'finagle']},
  'scala.base.base': {'num': 21, 'children': ['config', 'auth.user', 'json', 'consumer', 'base2', 'base-min']},
  'checkin': {'num': 2, 'children': ['base-min', 'recordv2', 'thrift.types']},
  'future': {'num': 3, 'children': ['scala.base.base', 'record']},
  'auth.user': {'num': 1, 'children': []},
  'acl': {'num': 2, 'children': []},
  'datetime': {'num': 2, 'children': ['base2', 'i18n.i18n']},
  'indexes.indexes': {'num': 1, 'children': ['record']},
  'ads.concrete': {'num': 9, 'children': ['ads.util', 'features', 'hairball', 'scala.metrics', 'scala.model', 'model2', 'public', 'queue2', 'actions.public', 'finders']},
  'api.util': {'num': 4, 'children': ['id', 'base-min', 'venue.venue', 'queue2', 'scala.types']},
  'less': {'num': 1, 'children': ['resource.resource']},
  'record': {'num': 36, 'children': ['geo.geo', 'base2', 'i18n.i18n', 'temphtml', 'scala.base.base', 'images', 'string', 'config', 'recordv2']},
  'geo.geo': {'num': 11, 'children': ['scala.base.base', 'base2', 'json', 'config', 'geo-min']},
  'concurrent': {'num': 1, 'children': []},
  'http': {'num': 6, 'children': ['api.util', 'auth.user', 'frontend.api', 'net.server', 'base-min']},
  'thrift.payments': {'num': 4, 'children': ['base-min', 'recordv2', 'thrift.types']},
}
